### ISSUE TITLE
Misleading behaviour in vignettes

### ISSUE THREAD

**Issue by Stat-Cook** [rikenbit/nnTensor#2]
In the vignettes when plotting the convergences they currently index as "[2:101]" - resulting in NA values at the end of the vector.

When I first checked this I was concerned there were numeric errors at the end of optimization, rather than the vectors aren't of this length.  I would suggest index instead as "[-1]" to drop the first (spurious) term and then the convergence vectors and plots are an accurate representation of the convergence.

**Comment by kokitsuyuzaki** [comment]
Thanks, I replaced all the [2:101] to [-1] in v1.1.13.
https://github.com/rikenbit/nnTensor/commit/1257383c32035c31951e44c7dd98c7dd8052cc32
